server:
  port: 8083
spring:
  profiles:
    active: native
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
zuul:
  routes:
    web-scrapping:
      url: http://localhost:8082
